[package]
name = "rust_ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11"
image = "0.25.9"
wgpu = "27.0.1"
pollster = "0.4.0"
bytemuck = "=1.24.0"
flume = "0.12.0"

[profile.dev]
opt-level = 3
